stages:
  stage_01_data_ingestion:
    cmd: python src/mlPipeline/pipeline/stage_01_data_ingestion.py
    deps:
    - configs/config.yaml
    - params.yaml
    - src/mlPipeline/pipeline/stage_01_data_ingestion.py
    - src/mlPipeline/components/data_ingestion.py
    - src/mlPipeline/config/configuration.py
    outs:
    - data/raw/creditcard.csv

  stage_02_data_validation:
    cmd: python src/mlPipeline/pipeline/stage_02_data_validation.py
    deps:
      - src/mlPipeline/pipeline/stage_02_data_validation.py
      - src/mlPipeline/components/data_validation.py
      - src/mlPipeline/config/configuration.py
      - configs/config.yaml
      - params.yaml
      - data/raw/creditcard.csv
      - configs/schema.yaml
    outs:
      - reports/validation/status.txt
      - reports/validation/report.json

