data_validation:
  duplicate_threshold: 0.2
  missing_threshold: 0.2
  
data_transformation:
  train_size: 0.70
  test_size: 0.15
  val_size: 0.15
  target_column: Class
  random_state: 42
  
model_training:
  random_state: 42
  models:
    logistic_regression:
      max_iter: 300 # can be tuned later
      class_weight: balanced # to address class imbalance, by penalizing misclassification of minority class
    random_forest:
      n_estimators: 200 # can be tuned later
      max_depth: 10 # can be tuned later
      class_weight: balanced
      
model_selection:
  metric: pr_auc