artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/1TZCQqA4yAPQTNm_emeYmgDUW53jarkwi/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/creditcard.zip
  unzip_dir: data/raw/

data_validation:
  input_file: data/raw/creditcard.csv
  schema_file_path: configs/schema.yaml
  report_dir: reports/validation
  report_json: report.json
  status_file: status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: data/raw/creditcard.csv
  preprocessed_data_path: artifacts/data_transformation/preprocessed
  transformer_object_file: artifacts/data_transformation/preprocessor.joblib
  stats_file_path: reports/data_transformation/preprocessor_stats.json

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/preprocessed/train.parquet
  val_data_path: artifacts/data_transformation/preprocessed/val.parquet
  trained_model_dir: artifacts/model_training/models
  best_model_path: artifacts/model_training/best_model.joblib
  metric_file_name: artifacts/model_training/train_metrics.json

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/preprocessed/test.parquet
  best_model_path: artifacts/model_training/best_model.joblib
  metric_file_name: artifacts/model_evaluation/evaluation_metrics.json

experiment:
  name: fraud_detection_experiment